---
- name: Setup /boot/firmware/config.txt
  ansible.builtin.blockinfile:
      path: /boot/firmware/config.txt
      block: |
          # PoE Hat Fan Speeds
          dtparam=poe_fan_temp0=70000
          dtparam=poe_fan_temp1=75000
          dtparam=poe_fan_temp2=80000
          dtparam=poe_fan_temp3=85000

          # Turn off PWR LED
          # dtparam=pwr_led_trigger=default-on
          # dtparam=pwr_led_activelow=off

          # Turn off ACT LED
          # dtparam=act_led_trigger=none
          # dtparam=act_led_activelow=off

          # Turn off Ethernet ACT LED
          # dtparam=eth_led0=4

          # Turn off Ethernet LNK LED
          # dtparam=eth_led1=4

- name: Reboot
  ansible.builtin.reboot:
